services:
  proxy-service:
    image: ghcr.io/sergeilisovoi22/cinemaabyss-proxy-service:latest
    build:
      context: ./_ext/proxy/cinemaabyss-proxy-service
      dockerfile: Dockerfile

  events-service:
    image: ghcr.io/sergeilisovoi22/events-service:latest
    build:
      context: ./_ext/events
      dockerfile: Dockerfile