apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjMlZ5WjJWcGJHbHpiM1p2YVRJeU9tZG9jRjlVYm5GeFJGazVZa0ZvZW1WVFRtMTBORVpsZFhwM2QwZFhOMUo0VUUwd1RYaENNV3M9In19fQ==
type: kubernetes.io/dockerconfigjson

