{{- if .Values.eventsService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.eventsService.replicas }}
  selector:
    matchLabels:
      app: events-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-service
    spec:
      imagePullSecrets:
        - name: {{ default "dockerconfigjson" .Values.imagePullSecretName }}
      containers:
        - name: events-service
          image: "{{ .Values.eventsService.image.repository }}:{{ .Values.eventsService.image.tag }}"
          imagePullPolicy: {{ .Values.eventsService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.eventsService.service.targetPort }}
          {{- with .Values.eventsService.env }}
          env:
            {{- range . }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.eventsService.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.eventsService.service.type }}
  selector:
    app: events-service
  ports:
    - name: http
      port: {{ .Values.eventsService.service.port }}
      targetPort: {{ .Values.eventsService.service.targetPort }}
{{- end }}
