name: Docker Build, Push & API Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/docker-build-push.yml'
  release:
    types: [ published ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # GHCR login с персональным токеном (секрет GHCR_PAT в ЭТОМ репозитории)
      - name: Log in to GHCR (with PAT)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: SergeiLisovoi22
          password: ${{ secrets.GHCR_PAT }}

      # ---------- подтягиваем микросервисы извне ----------
      - name: Checkout proxy-service repo
        uses: actions/checkout@v4
        with:
          repository: SergeiLisovoi22/cinemaabyss-proxy-service
          path: external/proxy
          token: ${{ secrets.GHCR_PAT }}

      - name: Checkout events-service repo
        uses: actions/checkout@v4
        with:
          repository: SergeiLisovoi22/events-service
          path: external/events
          token: ${{ secrets.GHCR_PAT }}

      # ---------- метаданные образов ----------
      - name: Meta (proxy)
        id: meta-proxy
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/sergeilisovoi22/cinemaabyss-proxy-service
          tags: |
            type=raw,value=latest
            type=sha,format=short
          labels: |
            org.opencontainers.image.source=https://github.com/SergeiLisovoi22/cinemaabyss-proxy-service

      - name: Meta (events)
        id: meta-events
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/sergeilisovoi22/events-service
          tags: |
            type=raw,value=latest
            type=sha,format=short
          labels: |
            org.opencontainers.image.source=https://github.com/SergeiLisovoi22/events-service

      # ---------- Build & Push: PROXY ----------
      - name: Build & Push (proxy-service)
        uses: docker/build-push-action@v5
        with:
          context: ./external/proxy
          # Если Dockerfile не в корне репо сервиса — раскомментируй и укажи путь:
          # file: ./external/proxy/Dockerfile
          push: true
          tags: ${{ steps.meta-proxy.outputs.tags }}
          labels: ${{ steps.meta-proxy.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---------- Build & Push: EVENTS ----------
      - name: Build & Push (events-service)
        uses: docker/build-push-action@v5
        with:
          context: ./external/events
          # file: ./external/events/Dockerfile
          push: true
          tags: ${{ steps.meta-events.outputs.tags }}
          labels: ${{ steps.meta-events.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---------- создаём CI-оверлей для compose (если не добавлен в репо) ----------
      - name: Ensure docker-compose.ci.yml exists
        run: |
          cat > docker-compose.ci.yml <<'YAML'
          services:
            proxy-service:
              image: ghcr.io/sergeilisovoi22/cinemaabyss-proxy-service:latest
              build: null
            events-service:
              image: ghcr.io/sergeilisovoi22/events-service:latest
              build: null
          YAML
          cat docker-compose.ci.yml

      # ---------- поднимаем окружение для тестов ----------
      - name: Docker Compose Up
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d
          echo "Wait for services to become healthy..."
          # мягкое ожидание основных сервисов
          for i in {1..30}; do
            curl -sf http://localhost:8080/health >/dev/null && break || sleep 2
          done
          docker ps

      # ---------- API тесты (newman в той же docker-сети) ----------
      - name: Run API tests (newman)
        run: |
          NET=$(docker network ls --format '{{.Name}}' | grep -E 'cinemaabyss|default' | head -n1)
          docker run --rm \
            --network="$NET" \
            -v "$PWD/tests/postman:/etc/newman" \
            postman/newman:alpine \
            run "/etc/newman/CinemaAbyss.postman_collection.json" \
            -e "/etc/newman/environments/docker.postman_environment.json" \
            --reporters cli

      - name: Docker Compose Down
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down -v
